# HPC run
stepwiseHPC = detectCores()
# source("smuf_run_0630_sd01_sml.R")
closeAllConnections()
source("smuf_run_0630_defheur_light1.R")
closeAllConnections()
source("smuf_run_0630_defheur_light4.R")
closeAllConnections()
source("smuf_run_0630_sd02_big")
closeAllConnections()
source("smuf_run_0630_defheur_03-04.R")
closeAllConnections()
source("smuf_run_0630_defheur_23-24.R")
